name: ecotte
description: "E-Commerce User App built in flutter and backend powered by nodejs"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  bottom_navy_bar: ^6.1.0
  smooth_page_indicator: ^1.2.0+3
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.8.0
  animations: ^2.0.11
  provider: ^6.1.2
  dropdown_button2: ^2.3.9
  flutter_cart: ^0.0.9
  get_storage: ^2.1.1
  flutter_login: ^5.0.0
  webview_flutter: ^4.10.0
  flutter_stripe: ^11.4.0
  razorpay_flutter: ^1.4.0
  onesignal_flutter: ^5.3.3
  image_picker: ^1.1.2
  flutter_dotenv: ^5.2.1
  intl: ^0.20.2
  pdf: ^3.10.4
  pdfx: ^2.9.2
  printing: ^5.11.0
  path_provider: ^2.1.3
  path: ^1.9.1
  permission_handler: ^12.0.1
  media_store_plus: ^0.1.3
  connectivity_plus: ^5.0.2
  device_info_plus: ^10.1.0
  open_file: ^3.3.2
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  # device_preview: ^1.2.0  # device_preview is outdated
  device_frame_plus: ^1.5.0

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/Ecotte_app_logo.png"
  image_path: "assets/Ecotte_app_logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/Ecotte_app_logo.png"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/fonts/Roboto-Regular.ttf
    - assets/fonts/Roboto-Bold.ttf
